name: 'Upsert PR Comment'
description: 'Create or update a PR comment with a unique identifier'
inputs:
  comment-identifier:
    description: 'Unique string to identify the comment (e.g., "🚀 PWA Validation Results")'
    required: true
  comment-body:
    description: 'The full body of the comment to create or update'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Upsert comment
      uses: actions/github-script@v8
      env:
        COMMENT_IDENTIFIER: ${{ inputs.comment-identifier }}
        COMMENT_BODY: ${{ inputs.comment-body }}
      with:
        script: |
          const commentIdentifier = process.env.COMMENT_IDENTIFIER;
          const commentBody = process.env.COMMENT_BODY;

          // Find existing comment from this bot
          const { data: comments } = await github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const botComment = comments.find(comment =>
            comment.user.type === 'Bot' &&
            comment.body.includes(commentIdentifier)
          );

          // Update existing comment or create new one
          if (botComment) {
            await github.rest.issues.updateComment({
              comment_id: botComment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
          } else {
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
          }
